export { default as dataBaseIcon } from './src/dataBase.vue'
export { default as downloadIcon } from './src/download.vue'
export { default as previewIcon } from './src/preview.vue'
export { default as uploadIcon } from './src/upload.vue'
export { default as outlineIcon } from './src/outline.vue'
export { default as deleteIcon } from './src/delete.vue'
export { default as upIcon } from './src/up.vue'
export { default as downIcon } from './src/down.vue'
